name: Bug Report
description: Report a bug or issue to help reproduce and fix it
labels: ["🔍 Issue : Bug - Awaiting Triage"]
body:
  - type: input
    attributes:
      label: Round ID / Commit SHA
      description: |
        Insert the round ID or server commit SHA here, to help us track where in the code's lifetime this bug occurred.
        You can find the commit SHA by using the `Show-Server-Revision` Verb in-game.
      placeholder: 69 or 955ae56ce4d5c571b1d81f1c9dd595faf2d13dd7
    validations:
      required: false
  - type: input
    attributes:
      label: Client Version
      description: |
        Put in your full client version in the format `xxx.yyyy` - for example `514.1578`
      placeholder: "123.4567"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description of the Issue
      description: |
        Describe the bug/issue you have encountered.
        Feel free to attach screenshots or videos as well.
      placeholder: I bought orange soda at the vending machine on Icebox, but it gave me lemon lime!
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction Steps
      description: |
        Please explain in detail how to reproduce the issue, in steps.
        Reports without proper reproduction steps or explanation are open to be ignored/closed by maintainers.
      placeholder: |
        1. Play on Icebox
        2. Go up to vendor
        3. Buy orange soda
        4. Get lemon lime instead
        5. Be sad.
    validations:
      required: false
