name: Changelogs - Lint Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited

jobs:
  validate:
    name: Lint Changelog
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.x'
          cache: 'pip'
          cache-dependency-path: '**/changelogs/requirements.txt'
      - name: Fetch dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r **/changelogs/requirements.txt
      - name: Lint and Validate Changelog
        run: |
          python tools/changelogs/ingest_pr_changelog.py -vv --check --strict ${{ github.repository }} ${{ github.event.number }} --auth ${{ secrets.GITHUB_TOKEN }}
